[workspace]
resolver = "2"
members = [
    "bouncing-pixel",
    "mini_gl_fb-random-walk-still-image",
    "mini_gl_fb-animation",
    "mandelbrot",
    "metaballs",
    "rainbow",
    "raycaster",
]

[profile.dev.package."*"]
opt-level = 3
