[workspace]
resolver = "2"
members = [
    "pulsating-heart",
    "snake",
    "particle-system",
    "animated-shader",
    "breakthrough",
    "interactive-fractal",
    "bevy-crash-course",
]

[profile.dev.package."*"]
opt-level = 3
